version: 0.2
phases:
  build:
    commands:
      - mkdir -p html
      - echo "<h1>krishna-therockstar1</h1>" > html/index.html
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - html/**/*
  discard-paths: no
